---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: run-pre-commits
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  run-pre-commits:
    name: Run pre-commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Run pre-commits
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--all-files"
