---
name: unit-tests
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
    paths:
      - gitcd/**
      - tests/**

env:
  POETRY_VERSION: 2.1.4

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - --version ${{env.POETRY_VERSION}}

      - name: Install dependencies
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install --no-interaction --no-ansi

      - name: Run unit tests
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry run pytest --cov=gitcd --cov-report=term-missing --cov-fail-under=70
